### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by MaxLevs**
Changelog:

* Add docker support
* Update node.js and next.js
* English translation

### CODE REVIEW

**Comment by MaxLevs** [comment]
Cannot find out what's with Vercel support. Detail is not accessable for me.

**Comment by MaxLevs** [comment]
I've cheked it. Versel is working well.

**Comment by oespino** [comment]
Sorry, the problem was that project settings were setup to use Node 14 version. I've changed it to Node 18. Thank you for your collaboration. How did you end up here?

**Comment by MaxLevs** [comment]
Well. My girlfriend is craizy about water sorter puzzles but some levels are very hard. I've searching for ready-made solutions and end up here :)

**Pull request merged**
